name: CI

on:
  pull_request:
  push:
    branches:
      - latest

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        rust: [stable]

    steps:
    - uses: actions/checkout@master

    - name: check
      run: cargo check --workspace --all-targets --features=test,all

    - name: tests
      run: cargo test --features=test,all
      env:
        RUST_BACKTRACE: short

    - name: workspace tests
      run: cargo test --workspace --features=test
      env:
        RUST_BACKTRACE: short

  check_fmt_and_docs:
    name: Checking fmt, clippy, and docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: install nightly
      run: rustup toolchain install nightly

    - name: clippy
      run: cargo clippy --workspace --all-targets --features=test,all

    - name: fmt
      run: cargo fmt --all -- --check

    - name: docs
      run: cargo +nightly doc --no-deps
